version: '3'
services:
  # metric-to-grafana
  metric:
    build: .
    container_name: metricslogs
    volumes:
      - ./:/code
    hostname: dockerhost
    environment:
      GRAFANA_ADDRESS: graphite
      GRAYLOG_ADDRESS: graylog:12201
      LOG_LEVEL: DEBUG
    networks:
      - grafana-net
      - graylog

  # graphite
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    networks:
      - grafana-net
    ports:
    - 80:80
    - 2003-2004:2003-2004
    - 8125:8125/udp
    - 8126:8126
    - 2023-2024:2023-2024
    volumes:
      - graphite_data:/opt/graphite/storage

  # Grafana latest image
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana_data:/var/lib/grafana

  # Graylog
  mongo:
    image: mongo:4.2
    networks:
      - graylog
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.1.5
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=XAa2ZoHrpvZkPKC7cpuNlk9HMutOQmdjL0zwj5dizSNfjjWUtOJm2IxoldC3pGO9
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ROOT_TIMEZONE=Europe/Copenhagen
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      - 5555:5555

networks:
  grafana-net:
  graylog:
    driver: bridge

volumes:
  grafana_data:
  graphite_data:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
